type Query {
  allCards(
    search: String
    types: [String]
    races: [String]
    attributes: [String]
    # pagination
    first: Int
    offset: Int
  ): CardsResult

  types: [Type]
  races: [Race]
  attributes: [Attribute]
}

type CardsResult {
  cards: [Card]
  totalCount: Int
}

type Card {
  id: Int!
  name: String!
  desc: String!
  type: String
  atk: Int!
  def: Int!
  level: Int!
  race: String
  attribute: String
  category: Int!
}

type Type {
  id: Int!
  name: String!
}

type Race {
  id: Int!
  name: String!
}

type Attribute {
  id: Int!
  name: String!
}
