type Query {
  allCards(
    search: String
    types: [String]
    races: [String]
    attributes: [String]
    # pagination
    page: Int
    pageSize: Int
  ): CardsResult

  types: [Type]
  races: [Race]
  attributes: [Attribute]
}

type CardsResult {
  cards: [Card]
  pageInfo: PageInfo
}

type PageInfo {
  total: Int!
  pageSize: Int!
  currentPage: Int!
  lastPage: Int!
  from: Int!
  to: Int!
}

type Card {
  id: Int!
  name: String!
  desc: String!
  type: String
  atk: Int!
  def: Int!
  level: Int!
  race: String
  attribute: String
  category: Int!
}

type Type {
  id: Int!
  type: String!
}

type Race {
  id: Int!
  race: String!
}

type Attribute {
  id: Int!
  attribute: String!
}
